# Generated by Django 3.2.3 on 2021-05-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sprite', models.CharField(default='', max_length=100)),
                ('main_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='main_type', to='pokemon.type')),
                ('sub_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_type', to='pokemon.type')),
            ],
        ),
    ]
