# Generated by Django 3.2.3 on 2021-05-17 13:22

from django.db import migrations, models
import pokemon.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20210514_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite',
            field=models.ImageField(blank=True, upload_to=pokemon.models.sprite_file),
        ),
    ]
