# Generated by Django 3.2.3 on 2021-05-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite',
            field=models.ImageField(blank=True, upload_to='sprite_file'),
        ),
    ]
