# Generated by Django 3.2.3 on 2021-05-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_pokemon_sprite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'pokemon'},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='main_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='main_type', to='pokemon.type', verbose_name='Main-type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sub_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_type', to='pokemon.type', verbose_name='Sub-type'),
        ),
    ]
